server:
  port: 90

spring:
  #基于配置文件的认证（不建议）
#  security:
#    user:
#      name: test
#      password: test
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springsecuritydemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai